spring:
  application:
    name: micro-auth-service
  config:
    import: optional:configserver:http://config-server-store:8888
#spring:
#  application:
#    name: micro-auth-service
#  datasource:
#    url: jdbc:mysql://msvc-mysql:3306/MicroFullAuth
#    username: root
#    password: ImNotlol12msvc
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#  sql:
#    init:
#      mode: always
#
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://eureka-server:8761/eureka/
##instance:
#server:
#  port: 8081
#
## JWT
#security:
#  jwt:
#    expiration-in-minutes: 600000
#    secret-key: ZXN0YSBlcyBtaSBjb250cmFzZW5hIHNlZ3VyYSAxMjM0NTY3ODkgQUJDYWJj
#
#paths
#request-paths:
#  paths:
#    # Restricción para rutas que terminan en '/status/hellCheck'
#    - uri: "/auth/status/hellCheck$"
#      methods: ["GET"]
#      roles: ["ROLE_ADMIN"]
#    - uri: "/user/status/hellCheck$"
#      methods: [ "GET" ]
#      roles: [ "ROLE_ADMIN" ]
#    - uri: "/book/status/hellCheck$"
#      methods: [ "GET" ]
#      roles: [ "ROLE_ADMIN" ]
#    - uri: "/catalog/status/hellCheck$"
#      methods: [ "GET" ]
#      roles: [ "ROLE_ADMIN" ]
#    # Restricción para rutas que comienzan con '/auth/open'
#    - uri: "/auth/open/.*"
#      methods: ["GET","POST"]
#    # Restriccion para rutas que comienzan con '/user/restrict'
#    - uri: "/user/restrict/.*"
#      methods: ["GET","POST"]
#      roles: ["ROLE_ADMIN","ROLE_USER"]
#    # Restriccion para rutas que comienzan con '/book/restrict'
#    - uri: "/book/restrict/.*"
#      methods: ["GET","POST","PUT","DELETE"]
#      roles: ["ROLE_ADMIN"]
#    # Restriccion para rutas que comienzan con '/order/restrict'
#    - uri: "/order/restrict/.*"
#      methods: ["GET","POST"]
#      roles: ["ROLE_ADMIN","ROLE_USER"]