version: '3.9'

networks:
  msvcs-book-store:
    driver: bridge

services:

  service-mysql:
    image: mysql
    container_name: msvc-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: MicroFullAuth
      MYSQL_ROOT_PASSWORD: ImNotlol12msvc
    restart: always
    networks:
      - msvcs-book-store

  config-server:
    image: config-server-store-img
    container_name: config-server-store
    ports:
      - "8888:8888"
    networks:
      - msvcs-book-store

  eureka-server:
#    build:
#      context: ./eureka-server # Ruta al Dockerfile
    image: eureka-server-store-img # Nombre y etiqueta de la imagen
    container_name: eureka-server-store
    ports:
      - "8761:8761"
#    env_file:
#      - .env
#    environment:
#      ACTIVE_PROFILE: ${activeProfile}
    depends_on: # Se ejecuta después de estos servicios
      - config-server
    networks:
      - msvcs-book-store

  gateway-server:
    image: gateway-server-store-img
    container_name: gateway-server-store
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - config-server
    networks:
      - msvcs-book-store

  auth-service:
    image: auth-service-store-img
    container_name: auth-service-store
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - config-server
      - service-mysql
    networks:
      - msvcs-book-store