server:
  port: 8080

#Nuevo1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


#gateway-service
spring:
  application:
    name: micro-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-users
          uri: lb://micro-auth-service
          predicates:
          - Path=/route/user/restrict/**, /route/auth/restrict/**
          filters:
          #- RewritePath=/user/auth/(?<segment>.*), /$\{segment}
          - StripPrefix=1
          - name: AuthRequestFilter
            args:
              message: Request with token [ ${spring.cloud.gateway.routes[0].uri} ]
              preLogger: true
              postLogger: true
        - id: auth-login
          uri: lb://micro-auth-service
          predicates:
          - Path=/route/auth/open/**
          filters:
          - StripPrefix=1
          - name: AuthRequestFilter
            args:
              message: Normal request [ ${spring.cloud.gateway.routes[1].uri} ]
              preLogger: false
              postLogger: true



